/**
 * graphLoader.js
 * Fetches graph_output.json (generated by the Python pipeline)
 * and returns the parsed data for the React dashboard.
 * 
 * Security: Validates JSON structure before returning to prevent
 * rendering tampered or malformed data.
 */

// Validates that the graph data has the expected structure
function validateGraphData(data) {
    if (!data || typeof data !== 'object') {
        throw new Error('Invalid graph data: not an object');
    }

    if (!Array.isArray(data.nodes)) {
        throw new Error('Invalid graph data: missing nodes array');
    }
    if (!Array.isArray(data.edges)) {
        throw new Error('Invalid graph data: missing edges array');
    }
    if (!Array.isArray(data.mismatches)) {
        throw new Error('Invalid graph data: missing mismatches array');
    }
    if (!data.summary || typeof data.summary !== 'object') {
        throw new Error('Invalid graph data: missing summary object');
    }

    // Validate node structure
    for (const node of data.nodes) {
        if (!node.id || !node.gstin || typeof node.score !== 'number') {
            throw new Error(`Invalid node data: ${JSON.stringify(node).slice(0, 100)}`);
        }
        // Sanitize string fields to prevent XSS if data comes from external source
        if (node.label) node.label = sanitizeString(node.label);
        if (node.state) node.state = sanitizeString(node.state);
    }

    // Validate mismatch structure
    for (const m of data.mismatches) {
        if (!m.id || !m.vendor || !m.gstin) {
            throw new Error(`Invalid mismatch data: ${JSON.stringify(m).slice(0, 100)}`);
        }
        // Sanitize text fields
        if (m.vendor) m.vendor = sanitizeString(m.vendor);
        if (m.audit) m.audit = sanitizeString(m.audit);
        if (m.inv) m.inv = sanitizeString(m.inv);
    }

    return data;
}

// Strip HTML tags and limit length to prevent XSS via data injection
function sanitizeString(str) {
    if (typeof str !== 'string') return String(str);
    return str
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#x27;')
        .slice(0, 500); // Cap length
}

export async function loadGraph() {
    const res = await fetch('/graph_output.json');
    if (!res.ok) throw new Error('Failed to load graph data');

    const data = await res.json();
    return validateGraphData(data);
}
